[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[project]
name = "anidb-mv"
version = "0.2.0"
description = "Command line client for AniDB"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "GPLv3"}
authors = [
  {name = "Jonas Bengtsson", email = "jonas@bengtsson.cc"},
]
urls = {Homepage = "https://github.com/ljb/anidb-mv"}
dependencies = [
  "pycryptodomex>=3.23",
]

[project.optional-dependencies]
dev = [
  "pytest>=8.4",
]

[project.scripts]
amv = "amv.amv:main"
amv-db = "amv.amv_db:main"

[tool.setuptools.packages.find]
include = ["amv*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
